project:
  type: website
  output-dir: docs

website:
  title: "PaleoAnth SiteMaps"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
        - Splash.qmd
format:
  html:
    theme: Sandstone
    css: styles.css
    toc: true
    
    
